version: 1

handlers:

  console:
    class: logging.StreamHandler
    #level: DEBUG
    stream: ext://sys.stderr
    formatter: simpleFormatter

  file:
    class: logging.FileHandler
    filename: /tmp/agrischemas-dfw-pipeline.log
    mode: w
    #level: DEBUG
    formatter: simpleFormatter

formatters:
  simpleFormatter:
    #class: !!python/name:logging.Formatter
    #class: logging.Formatter
    format: '%(name)-10s %(threadName)s %(asctime)s %(levelname)-5s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'


root:
  level: INFO
  handlers: [console, file]
  #handlers: [ console ]
