jobs: 8
local-cores: 4
cluster: "sbatch --chdir=/home/data/knetminer/software/agri-schemas/dfw-dataset/gxa --cpus-per-task=6 --qos=long --time=1-0:0:0  -o .snakemake/log/slurm-{rule}-{wildcards.exp_acc}.out -e .snakemake/log/slurm-{rule}-{wildcards.exp_acc}.out"
