jobs: 16
cluster: "sbatch --chdir=/home/data/knetminer/software/agri-schemas/dfw-dataset/gxa --cpus-per-task=8 --qos=long --time=1-0:0:0  -o .snakemake/log/slurm-{rule}-{wildcards}.out -e .snakemake/log/slurm-{rule}-{wildcards}.out"
